#!/usr/bin/env bash
# Aether Cloud OS — configuration generation.
#
# Writes the secrets layout and `.env` the backend's config.ts actually
# requires. Node installs the source tree into $AETHER_INSTALL_DIR/src and
# the built frontend into $AETHER_STATIC_DIR; this file only writes data:
# secret files (600), the .env file (600), and the JSON state/bootstrap files.

# Template rendered by scripts/install.sh before sourcing the libs.
AETHER_DOMAIN_TEMPLATE="{{AETHER_DOMAIN_PLACEHOLDER}}"
AETHER_ADMIN_EMAIL_TEMPLATE="{{AETHER_ADMIN_EMAIL_PLACEHOLDER}}"

validate_domain() {
    local domain="$1"

    if [ -z "$domain" ]; then
        fatal "A domain name is required. The installer cannot issue certificates or route traffic without one."
    fi

    if [ "${#domain}" -gt 253 ]; then
        fatal "Domain too long (max 253 characters): $domain"
    fi

    if [[ "$domain" == *..* ]] || [[ ! "$domain" =~ ^[A-Za-z0-9]([A-Za-z0-9.-]*[A-Za-z0-9])?$ ]] || [[ "$domain" == */* ]]; then
        fatal "Domain is not RFC 1035 compliant: $domain"
    fi
}

validate_email() {
    local email="$1"
    if [[ ! "$email" =~ ^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$ ]]; then
        fatal "Admin email does not look like an email address: $email"
    fi
}

prompt_for_settings() {
    # Skipped when the operator already answered (flags or --yes), or when
    # there is no TTY to read from — the defaults documented below then apply.
    if [ "${AETHER_YES:-false}" = "true" ] || [ ! -t 0 ]; then
        info "Non-interactive install: using domain '$AETHER_DOMAIN_TEMPLATE', email '$AETHER_ADMIN_EMAIL_TEMPLATE'"
        AETHER_DOMAIN="$AETHER_DOMAIN_TEMPLATE"
        AETHER_ADMIN_EMAIL="$AETHER_ADMIN_EMAIL_TEMPLATE"
    else
        printf 'Domain for this instance [%s]: ' "$AETHER_DOMAIN_TEMPLATE"
        read -r answer || true
        AETHER_DOMAIN="${answer:-$AETHER_DOMAIN_TEMPLATE}"
        printf 'Admin email for certificate notices [%s]: ' "$AETHER_ADMIN_EMAIL_TEMPLATE"
        read -r answer || true
        AETHER_ADMIN_EMAIL="${answer:-$AETHER_ADMIN_EMAIL_TEMPLATE}"
    fi

    validate_domain "$AETHER_DOMAIN"
    validate_email "$AETHER_ADMIN_EMAIL"
    export AETHER_DOMAIN AETHER_ADMIN_EMAIL
}

generate_env_file() {
    # Full contract §8.1: every value the backend schema demands, no more.
    local env_file="${AETHER_INSTALL_DIR}/.env"

    if [ -f "$env_file" ]; then
        local backup="${AETHER_INSTALL_DIR}/backups/env-backup-$(date +%Y%m%d-%H%M%S).txt"
        mkdir -p "$(dirname "$backup")"
        cp "$env_file" "$backup"
        info "Existing .env backed up to $backup"
    fi

    info "Writing $env_file"
    umask 077
    cat > "$env_file" <<EOF
# Generated by the Aether installer — do not hand-edit secrets on this line or below.
NODE_ENV=production
PORT=3000
HOST=0.0.0.0
BASE_URL=https://${AETHER_DOMAIN}
ALLOWED_ORIGINS=https://${AETHER_DOMAIN}

POSTGRES_USER=aether
POSTGRES_PASSWORD=${SECRET_DB_PASSWORD}
POSTGRES_DB=aether
DATABASE_URL=postgresql://aether:${SECRET_DB_PASSWORD}@postgres:5432/aether
REDIS_PASSWORD=${SECRET_REDIS_PASSWORD}
REDIS_URL=redis://:${SECRET_REDIS_PASSWORD}@redis:6379

JWT_SECRET=${SECRET_JWT}
JWT_ACCESS_TOKEN_EXPIRY=15m
JWT_REFRESH_TOKEN_EXPIRY=30d
ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
SESSION_SECRET=${SECRET_SESSION}

AETHER_WORKSPACE_ROOT=/data/workspace
UPLOAD_DIR=/data/uploads
AETHER_STATIC_DIR=/opt/aether/static
TERMINAL_ENABLED=true
TERMINAL_MAX_SESSIONS=10
AETHER_PROCESS_SIGNAL_ENABLED=false
TRUST_PROXY_HOPS=1

AETHER_BOOTSTRAP_TOKEN=${SECRET_BOOTSTRAP_TOKEN}
AETHER_INSTANCE_ID=${SECRET_INSTANCE_ID}

AETHER_DOMAIN=${AETHER_DOMAIN}
AETHER_ADMIN_EMAIL=${AETHER_ADMIN_EMAIL}
AETHER_VERSION=${AETHER_VERSION}
EOF
    chmod 600 "$env_file"
}

write_instance_metadata() {
    # instance.json is the human-readable record; install.state is the
    # key=value résumé the orchestrator checkpoints into (contract §13.2).
    local now
    now=$(date -u '+%Y-%m-%dT%H:%M:%SZ')

    cat > "${AETHER_INSTALL_DIR}/instance.json" <<EOF
{"installationId":"${AETHER_INSTALLATION_ID:-unknown}","version":"${AETHER_VERSION}","domain":"${AETHER_DOMAIN}","createdAt":"${now}"}
EOF

    state_set installation_id "${AETHER_INSTALLATION_ID:-unknown}"
    state_set version "$AETHER_VERSION"
    state_set domain "$AETHER_DOMAIN"
}

configure_system() {
    stage "Configuring installation"

    prompt_for_settings

    mkdir -p "$AETHER_INSTALL_DIR/data/workspace" "$AETHER_INSTALL_DIR/data/uploads"
    mkdir -p "$AETHER_INSTALL_DIR/logs" "$AETHER_INSTALL_DIR/backups"
    mkdir -p "$AETHER_INSTALL_DIR/caddy" "$AETHER_INSTALL_DIR/secrets"
    chmod 700 "$AETHER_INSTALL_DIR/secrets"

    generate_all_secrets
    generate_env_file
    write_instance_metadata

    info "Configuration written to $AETHER_INSTALL_DIR"
}
