#!/usr/bin/env bash
# Aether Cloud OS — configuration generation.
#
# Writes the secrets layout and `.env` the backend's config.ts actually
# requires. Node installs the source tree into $AETHER_INSTALL_DIR/src and
# the built frontend into $AETHER_STATIC_DIR; this file only writes data:
# secret files (600), the .env file (600), and the JSON state/bootstrap files.

# Template rendered by scripts/install.sh before sourcing the libs.
AETHER_DOMAIN_TEMPLATE="{{AETHER_DOMAIN_PLACEHOLDER}}"
AETHER_ADMIN_EMAIL_TEMPLATE="{{AETHER_ADMIN_EMAIL_PLACEHOLDER}}"

validate_domain() {
    local domain="$1"

    # Empty means IP-only mode: Caddy serves HTTP on port 80 and no ACME
    # certificate is requested. A domain is still required for HTTPS mode.
    [ -z "$domain" ] && return 0

    if [ "${#domain}" -gt 253 ]; then
        fatal "Domain too long (max 253 characters): $domain"
    fi

    [[ "$domain" != *..* ]] || fatal "Domain contains an empty label: $domain"
    [[ "$domain" != */* ]] || fatal "Domain must not contain '/': $domain"
    [[ "$domain" != *["]"]* ]] || fatal "Domain contains invalid characters: $domain"
    [[ "$domain" =~ ^[A-Za-z0-9.-]+$ ]] || fatal "Domain is not RFC 1035 compliant: $domain"

    local label
    IFS='.' read -r -a labels <<< "$domain"
    for label in "${labels[@]}"; do
        [ -n "$label" ] || fatal "Domain contains an empty label: $domain"
        [ "${#label}" -le 63 ] || fatal "Domain label is longer than 63 characters: $label"
        [[ "$label" =~ ^[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?$ ]] || \
            fatal "Domain label is not RFC 1035 compliant: $label"
    done
}

validate_email() {
    local email="$1"
    # Email is optional in IP-only mode; Caddy's local default is sufficient.
    [ -z "$email" ] && return 0
    if [[ ! "$email" =~ ^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$ ]]; then
        fatal "Admin email does not look like an email address: $email"
    fi
}

prompt_for_settings() {
    # Never overwrite values supplied through --domain/--email or the
    # environment. This is especially important for `curl | bash`, where
    # stdin is not a TTY and the old implementation silently replaced CLI
    # values with the literal template placeholders.
    local domain="${AETHER_DOMAIN:-}"
    local email="${AETHER_ADMIN_EMAIL:-}"

    if [ -z "$domain" ]; then
        if [ "${AETHER_YES:-false}" = "true" ] || [ ! -t 0 ]; then
            domain="$AETHER_DOMAIN_TEMPLATE"
        else
            printf 'Domain for this instance (leave blank for IP-only HTTP): '
            read -r domain || true
        fi
    fi

    if [ -z "$email" ]; then
        if [ "${AETHER_YES:-false}" = "true" ] || [ ! -t 0 ]; then
            email="$AETHER_ADMIN_EMAIL_TEMPLATE"
        else
            printf 'Admin email for certificate notices: '
            read -r email || true
        fi
    fi

    # A packaged release may replace these placeholders with defaults. If it
    # did not, preserve an empty value for supported IP-only mode.
    [[ "$domain" != *'{{'* ]] || domain=""
    [[ "$email" != *'{{'* ]] || email=""

    validate_domain "$domain"
    validate_email "$email"
    AETHER_DOMAIN="$domain"
    AETHER_ADMIN_EMAIL="$email"
    export AETHER_DOMAIN AETHER_ADMIN_EMAIL
}

generate_env_file() {
    # Full contract §8.1: every value the backend schema demands, no more.
    local env_file="${AETHER_INSTALL_DIR}/.env"

    if [ -f "$env_file" ]; then
        local backup="${AETHER_INSTALL_DIR}/backups/env-backup-$(date +%Y%m%d-%H%M%S).txt"
        mkdir -p "$(dirname "$backup")"
        cp "$env_file" "$backup"
        info "Existing .env backed up to $backup"
    fi

    info "Writing $env_file"
    umask 077
    cat > "$env_file" <<EOF
# Generated by the Aether installer — do not hand-edit secrets on this line or below.
NODE_ENV=production
PORT=3000
HOST=0.0.0.0
BASE_URL=$( if [ -n "${AETHER_DOMAIN}" ] && [ "${AETHER_NO_HTTPS:-false}" != "true" ]; then printf 'https://%s' "${AETHER_DOMAIN}"; elif [ -n "${AETHER_DOMAIN}" ]; then printf 'http://%s' "${AETHER_DOMAIN}"; else printf 'http://127.0.0.1'; fi )
ALLOWED_ORIGINS=$( if [ -n "${AETHER_DOMAIN}" ] && [ "${AETHER_NO_HTTPS:-false}" != "true" ]; then printf 'https://%s' "${AETHER_DOMAIN}"; elif [ -n "${AETHER_DOMAIN}" ]; then printf 'http://%s' "${AETHER_DOMAIN}"; else printf 'http://127.0.0.1,http://localhost'; fi )

POSTGRES_USER=aether
POSTGRES_PASSWORD=${SECRET_DB_PASSWORD}
POSTGRES_DB=aether
DATABASE_URL=postgresql://aether:${SECRET_DB_PASSWORD}@postgres:5432/aether
REDIS_PASSWORD=${SECRET_REDIS_PASSWORD}
REDIS_URL=redis://:${SECRET_REDIS_PASSWORD}@redis:6379

JWT_SECRET=${SECRET_JWT}
JWT_ACCESS_TOKEN_EXPIRY=15m
JWT_REFRESH_TOKEN_EXPIRY=30d
ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
SESSION_SECRET=${SECRET_SESSION}

AETHER_WORKSPACE_ROOT=/data/workspace
UPLOAD_DIR=/data/uploads
AETHER_STATIC_DIR=/opt/aether/static
TERMINAL_ENABLED=true
TERMINAL_MAX_SESSIONS=10
AETHER_PROCESS_SIGNAL_ENABLED=false
TRUST_PROXY_HOPS=1

AETHER_BOOTSTRAP_TOKEN=${SECRET_BOOTSTRAP_TOKEN}
AETHER_INSTANCE_ID=${SECRET_INSTANCE_ID}

AETHER_DOMAIN=${AETHER_DOMAIN}
AETHER_ADMIN_EMAIL=${AETHER_ADMIN_EMAIL}
AETHER_VERSION=${AETHER_VERSION}
EOF
    chmod 600 "$env_file"
}

write_instance_metadata() {
    # instance.json is the human-readable record; install.state is the
    # key=value résumé the orchestrator checkpoints into (contract §13.2).
    local now
    now=$(date -u '+%Y-%m-%dT%H:%M:%SZ')

    cat > "${AETHER_INSTALL_DIR}/instance.json" <<EOF
{"installationId":"${AETHER_INSTALLATION_ID:-unknown}","version":"${AETHER_VERSION}","domain":"${AETHER_DOMAIN}","createdAt":"${now}"}
EOF

    state_set installation_id "${AETHER_INSTALLATION_ID:-unknown}"
    state_set version "$AETHER_VERSION"
    state_set domain "$AETHER_DOMAIN"
}

configure_system() {
    stage "Configuring installation"

    prompt_for_settings
    check_dns_resolution

    mkdir -p "$AETHER_INSTALL_DIR/data/workspace" "$AETHER_INSTALL_DIR/data/uploads"
    mkdir -p "$AETHER_INSTALL_DIR/logs" "$AETHER_INSTALL_DIR/backups"
    mkdir -p "$AETHER_INSTALL_DIR/caddy" "$AETHER_INSTALL_DIR/secrets"
    chmod 700 "$AETHER_INSTALL_DIR/secrets"

    generate_all_secrets
    generate_env_file
    write_instance_metadata

    info "Configuration written to $AETHER_INSTALL_DIR"
}
